"""
F1RaceOps — FastAPI app entrypoint.

Run locally:
    uvicorn backend.main:app --reload --port ${API_PORT:-8000}

Interactive API docs (auto-generated by FastAPI from the routes + Pydantic
schemas) are available at /docs once running.
"""

import os

from dotenv import load_dotenv
from fastapi import FastAPI

from backend.api import races_router

load_dotenv()

app = FastAPI(
    title="F1RaceOps API",
    description="Race strategy platform: real F1 race data and Monte Carlo pit-strategy simulation.",
    version="0.1.0",
)

app.include_router(races_router)


@app.get("/health")
def health_check():
    """Basic liveness check — not tied to the database, just confirms the app is up."""
    return {"status": "ok", "env": os.environ.get("APP_ENV", "unknown")}