"""
F1RaceOps — FastAPI app entrypoint.

Run locally:
    uvicorn backend.main:app --reload --port ${API_PORT:-8000}

Interactive API docs (auto-generated by FastAPI from the routes + Pydantic
schemas) are available at /docs once running.
"""

import os

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from backend.api import races_router, strategy_router

load_dotenv()

app = FastAPI(
    title="F1RaceOps API",
    description="Race strategy platform: real F1 race data and Monte Carlo pit-strategy simulation.",
    version="0.1.0",
)

cors_origins = os.environ.get("CORS_ORIGINS", "http://localhost:3000").split(",")
app.add_middleware(
    CORSMiddleware,
    allow_origins=cors_origins,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(races_router)
app.include_router(strategy_router)


@app.get("/health")
def health_check():
    """Basic liveness check — not tied to the database, just confirms the app is up."""
    return {"status": "ok", "env": os.environ.get("APP_ENV", "unknown")}