"""initial schema

Revision ID: 3835187f88a2
Revises: 
Create Date: 2026-08-08 02:54:48.382579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3835187f88a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_ref', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuits_circuit_ref'), 'circuits', ['circuit_ref'], unique=True)
    op.create_table('constructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('constructor_ref', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constructors_constructor_ref'), 'constructors', ['constructor_ref'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_ref', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('given_name', sa.String(length=100), nullable=False),
    sa.Column('family_name', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_driver_ref'), 'drivers', ['driver_ref'], unique=True)
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('total_laps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round', name='uq_race_season_round')
    )
    op.create_index(op.f('ix_races_season'), 'races', ['season'], unique=False)
    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time_ms', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('sector_1_ms', sa.Integer(), nullable=True),
    sa.Column('sector_2_ms', sa.Integer(), nullable=True),
    sa.Column('sector_3_ms', sa.Integer(), nullable=True),
    sa.Column('compound', sa.String(length=20), nullable=True),
    sa.Column('tyre_life', sa.Integer(), nullable=True),
    sa.Column('stint_number', sa.Integer(), nullable=True),
    sa.Column('is_accurate', sa.Boolean(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', 'lap_number', name='uq_lap_race_driver_lapnum')
    )
    op.create_index(op.f('ix_laps_driver_id'), 'laps', ['driver_id'], unique=False)
    op.create_index(op.f('ix_laps_race_id'), 'laps', ['race_id'], unique=False)
    op.create_table('pit_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('stop_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', 'stop_number', name='uq_pitstop_race_driver_num')
    )
    op.create_index(op.f('ix_pit_stops_driver_id'), 'pit_stops', ['driver_id'], unique=False)
    op.create_index(op.f('ix_pit_stops_race_id'), 'pit_stops', ['race_id'], unique=False)
    op.create_table('race_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('grid_position', sa.Integer(), nullable=True),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_result_race_driver')
    )
    op.create_index(op.f('ix_race_results_driver_id'), 'race_results', ['driver_id'], unique=False)
    op.create_index(op.f('ix_race_results_race_id'), 'race_results', ['race_id'], unique=False)
    op.create_table('stints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('stint_number', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(length=20), nullable=True),
    sa.Column('lap_start', sa.Integer(), nullable=False),
    sa.Column('lap_end', sa.Integer(), nullable=False),
    sa.Column('tyre_life_start', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', 'stint_number', name='uq_stint_race_driver_num')
    )
    op.create_index(op.f('ix_stints_driver_id'), 'stints', ['driver_id'], unique=False)
    op.create_index(op.f('ix_stints_race_id'), 'stints', ['race_id'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('air_temp', sa.Float(), nullable=True),
    sa.Column('track_temp', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Boolean(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'lap_number', name='uq_weather_race_lapnum')
    )
    op.create_index(op.f('ix_weather_race_id'), 'weather', ['race_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_race_id'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_stints_race_id'), table_name='stints')
    op.drop_index(op.f('ix_stints_driver_id'), table_name='stints')
    op.drop_table('stints')
    op.drop_index(op.f('ix_race_results_race_id'), table_name='race_results')
    op.drop_index(op.f('ix_race_results_driver_id'), table_name='race_results')
    op.drop_table('race_results')
    op.drop_index(op.f('ix_pit_stops_race_id'), table_name='pit_stops')
    op.drop_index(op.f('ix_pit_stops_driver_id'), table_name='pit_stops')
    op.drop_table('pit_stops')
    op.drop_index(op.f('ix_laps_race_id'), table_name='laps')
    op.drop_index(op.f('ix_laps_driver_id'), table_name='laps')
    op.drop_table('laps')
    op.drop_index(op.f('ix_races_season'), table_name='races')
    op.drop_table('races')
    op.drop_index(op.f('ix_drivers_driver_ref'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_constructors_constructor_ref'), table_name='constructors')
    op.drop_table('constructors')
    op.drop_index(op.f('ix_circuits_circuit_ref'), table_name='circuits')
    op.drop_table('circuits')
    # ### end Alembic commands ###
