"""add cumulative_time_ms to laps

Revision ID: 5d462bf49276
Revises: 3835187f88a2
Create Date: 2026-08-08 13:26:16.668035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d462bf49276'
down_revision: Union[str, None] = '3835187f88a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laps', sa.Column('cumulative_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laps', 'cumulative_time_ms')
    # ### end Alembic commands ###
